import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * http://github.com/vanniktech/gradle-maven-publish-plugin/
   */
  const val gradle_maven_publish_plugin: String = "com.vanniktech:gradle-maven-publish-plugin:" +
      Versions.gradle_maven_publish_plugin

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_ext_junit: String = "androidx.test.ext:junit:" +
      Versions.androidx_test_ext_junit

  /**
   * https://developer.android.com/testing
   */
  const val androidx_test_runner: String = "androidx.test:runner:" + Versions.androidx_test_runner

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_annotation_processing_gradle: String =
      "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:" + Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib_jdk7: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:" +
      Versions.org_jetbrains_kotlin

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val core_common: String = "androidx.arch.core:core-common:" + Versions.androidx_arch_core

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val core_runtime: String = "androidx.arch.core:core-runtime:" + Versions.androidx_arch_core

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val core_testing: String = "androidx.arch.core:core-testing:" + Versions.androidx_arch_core

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val work_runtime_ktx: String = "androidx.work:work-runtime-ktx:" + Versions.work_runtime_ktx

  /**
   * https://developer.android.com/topic/libraries/architecture/index.html
   */
  const val room_compiler: String = "androidx.room:room-compiler:" + Versions.room_compiler

  /**
   * https://developer.android.com/testing
   */
  const val espresso_core: String = "androidx.test.espresso:espresso-core:" + Versions.espresso_core

  /**
   * http://assertj.org
   */
  const val assertj_core: String = "org.assertj:assertj-core:" + Versions.assertj_core

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * http://junit.org
   */
  const val junit_junit: String = "junit:junit:" + Versions.junit_junit

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val appcompat: String = "androidx.appcompat:appcompat:" + Versions.appcompat

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

  /**
   * http://mockk.io
   */
  const val mockk_android: String = "io.mockk:mockk-android:" + Versions.io_mockk

  /**
   * http://mockk.io
   */
  const val mockk: String = "io.mockk:mockk:" + Versions.io_mockk

  /**
   * https://github.com/JakeWharton/timber
   */
  const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

  /**
   * https://github.com/square/okhttp
   */
  const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://github.com/google/gson
   */
  const val gson: String = "com.google.code.gson:gson:" + Versions.gson
}
